### ISSUE TITLE
Add Bluetooth support

### ISSUE THREAD

**Issue by RyuzakiKK** [flathub/org.gnome.Keysign#1]
Right now our manifest doesn't list the required Bluetooth dependencies, so we can only transfer the key with Avahi.

I opened this issue to not forget. This is a work in progress.

**Comment by muelli** [comment]
cf. https://github.com/flatpak/flatpak/issues/1719

**Comment by RyuzakiKK** [comment]
Bluetooth support added with 32ec75a
