### ISSUE TITLE
Doesn’t work on Wayland

### ISSUE THREAD

**Issue by jurf** [flathub/org.gnome.Keysign#14]
This is the error I get:
```
$ org.gnome.Keysign 
Traceback (most recent call last):
  File "/app/bin/gnome-keysign", line 10, in <module>
    sys.exit(main())
  File "/app/lib/python3.7/site-packages/keysign/__init__.py", line 22, in main
    from . import app
  File "/app/lib/python3.7/site-packages/keysign/app.py", line 31, in <module>
    from twisted.internet import gtk3reactor
  File "/app/lib/python3.7/site-packages/twisted/internet/gtk3reactor.py", line 38, in <module>
    "Gtk3 requires X11, and no DISPLAY environment variable is set")
ImportError: Gtk3 requires X11, and no DISPLAY environment variable is set
```

**Comment by RyuzakiKK** [comment]
FTR is Twisted that is throwing this error https://gitlab.kitware.com/third-party/twisted/-/blob/3b116ebd/src/twisted/internet/gtk3reactor.py#L38

**Comment by muelli** [comment]
so.. how does one report a bug against twisted...?

**Comment by RyuzakiKK** [comment]
It should be here https://twistedmatrix.com/trac/report

**Comment by muelli** [comment]
@jurf do you mind creating a bug in the upstream bug tracker?

**Comment by muelli** [comment]
https://twistedmatrix.com/trac/ticket/9904

**Comment by muelli** [comment]
I guess we can disable the wayland socket as the app is not compatible with Wayland. I have done so in 1c3dd518f1c45c65f596eb16e334853ffcf51857.
