### ISSUE TITLE
update Gnome runtime

### ISSUE THREAD

**Issue by junefish** [flathub/org.gnome.Keysign#20]
When I run `flatpak update` I get the following:
```
$ flatpak update
Looking for updates…
Info: org.gnome.Platform//40 is end-of-life, with reason:
   The GNOME 40 runtime is no longer supported as of March 21, 2022. Please
ask your application developer to migrate to a supported platform.
Applications using this runtime:
   org.gnome.Keysign
```

Not sure what other info would be helpful to provide but happy to do so upon request.

**Comment by RyuzakiKK** [comment]
Thanks for pointing that out.

The runtime has been already updated with https://github.com/flathub/org.gnome.Keysign/commit/c2ff47b48c747b3bdd9afcd1ce9e12d5c4ccc4fb, but apparently the build failed, so it is still using the older GNOME 40 runtime.

**Comment by junefish** [comment]
Is there something I can do to fix it?

**Comment by RyuzakiKK** [comment]
I updated the dependencies and that fixed the compilation error.

In a few hours the updated version of Keysign should reach Flathub repos.

**Comment by junefish** [comment]
Thanks, this seems to be fixed now.
